### ISSUE TITLE
AbortController: import vs node global

### ISSUE THREAD

**Issue by tkurki** [ferdikoomen/openapi-typescript-codegen#989]
The generate code includes `import { AbortController } from 'abort-controller'` in [request.ts](https://github.com/ferdikoomen/openapi-typescript-codegen/blob/8d5e458c08a4ad8d59ac54b34bd9113d21d8045e/src/templates/core/node/request.hbs#L3).

This does not work with Node's global `AbortController` that has been there since at least Node 14.

How do I get this to work with node-fetch & Node >= 14?

I am not very familiar with ts intricacies, so I may be doing something wrong here.

**Comment by ferdikoomen** [comment]
@tkurki good find, I'm all for dropping this import, this would break for Node < 14 users, however it should be an easy upgrade (or they can keep using the current version of the generator). I pushed a fix into the maim branch, will release a new version by the end of the day: 0.21.0

**Comment by SpaseESG** [comment]
@ferdikoomen  I am still getting an error when using 0.21.0 and generating a client.

**Comment by tkurki** [comment]
Womm. Thank you!

**Comment by ferdikoomen** [comment]
@SpaseESG What error are you getting? Could you send the the command you are using to generate the client and the error you are seeing? Cheers

**Comment by DevasiaThomas** [comment]
Hi @ferdikoomen 
I had to fall back to typescript 4.6 to get rid of this error, seems like node-fetch's definition of AbortSignal is out of sync with the one from typescript 4.7 onwards.. 

This is the error
```
generated/core/request.ts:209:9 - error TS2322: Type 'AbortSignal' is not assignable to type 'import("/.../node_modules/@types/node-fetch/externals").AbortSignal'.
  Types of property 'onabort' are incompatible.
    Type '((this: AbortSignal, ev: Event) => any) | null' is not assignable to type '((this: AbortSignal, event: any) => any) | null'.
      Type '(this: AbortSignal, ev: Event) => any' is not assignable to type '(this: AbortSignal, event: any) => any'.
        The 'this' types of each signature are incompatible.
          Type 'AbortSignal' is missing the following properties from type 'AbortSignal': reason, throwIfAborted

209         signal: controller.signal,
            ~~~~~~

  node_modules/@types/node-fetch/index.d.ts:52:5
    52     signal?: AbortSignal | null | undefined;
           ~~~~~~
    The expected type comes from property 'signal' which is declared here on type 'RequestInit'

```

**Comment by anderskristo** [comment]
@ferdikoomen Is it possible to solve this for typescript < 4.7?

**Comment by LefanTan** [comment]
I am getting the same error on typescript 4.9.5

**Comment by anderskristo** [comment]
@LefanTan I went with the Axios client since it was to much of a hassle to get working with my setup.

**Comment by flylo** [comment]
I'm getting the same thing:

```
Compiling TypeScript files for project "unit-client"...
packages/client/core/request.ts:211:17 - error TS2352: Conversion of type 'AbortSignal' to type 'import("/usr/home/src/repo/node_modules/@types/node-fetch/externals").AbortSignal' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'throwIfAborted' is missing in type 'AbortSignal' but required in type 'import("/usr/home/src/repo/node_modules/@types/node-fetch/externals").AbortSignal'.

211         signal: controller.signal as AbortSignal,
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/node-fetch/externals.d.ts:23:5
    23     throwIfAborted(): void;
           ~~~~~~~~~~~~~~~~~~~~~~~

```
